### ISSUE TITLE
Myblog的一个数据库连接错误

### ISSUE THREAD

**Issue by davidan106** [lenve/JavaEETest#2]
经过修改jdbc.properties之后，还是无法连接数据库，报错如下：
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by lostme037** [comment]
@davidan106 在MyMVCConfig类里，注入dataSource的时候作者把数据库信息写死了，这里改一下就好。

**Comment by jzyGithub** [comment]
改了以后报空指针异常

**Comment by lenve** [comment]
@davidan106 
我的失误，密码在这里改https://github.com/lenve/JavaEETest/blob/master/MyBlog/src/main/java/org/sang/config/MyMVCConfig.java

**Comment by jzyGithub** [comment]
dbConfig为null，这是为什么啊
