### ISSUE TITLE
web.xml文件呢

### ISSUE THREAD

**Issue by XCAndrew** [lenve/JavaEETest#3]
这东西没见了，项目真的能运行吗。。。

**Comment by lenve** [comment]
可以运行啊！web.xml文件可以用xml写也可以用Java写啊

**Comment by lenve** [comment]
注意查看这个文件`MyBlog/src/main/java/org/sang/config/WebInitializer.java`

**Comment by jzyGithub** [comment]
涨姿势了 谢谢

**Comment by dolceDawn** [comment]
Test开头的项目，main函数用什么方式运行啊（applet，applciation，Junit...?），用的idea开发工具,望不吝赐教
