### ISSUE TITLE
下载不下来。。。

### ISSUE THREAD

**Issue by NoriSang** [lenve/JavaEETest#4]
为什么不能下载呢

**Comment by ycountJavaXuan** [comment]
看清楚行不？
有病？
在 2017年6月19日，15:50，NoriSang <notifications@github.com<mailto:notifications@github.com>> 写道：


为什么不能下载呢

**Comment by NoriSang** [comment]
对不起。。。弄错了。。对不起

**Comment by ycountJavaXuan** [comment]
= =！态度这么好。
你也没说你要下啥啊- -！
在 2017年6月19日，16:17，NoriSang <notifications@github.com<mailto:notifications@github.com>> 写道：


对不起。。。弄错了。。对不起
